#Sources 
:sources: 
  Contact: 
    :poll_interval: 30
  Opportunity: 
    :poll_interval: 30
  Account: 
    :poll_interval: 30
  Lead: 
    :poll_interval: 30
 
:test: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/api/application/
:production: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/api/application/
:development: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/api/application/
